<?php
require '../connection.php';

// Get the medicine ID from the form or URL parameter
$medicineId = isset($_GET['medicine_id']) ? $_GET['medicine_id'] : '';
$medicineId = isset($_POST['medicine_id']) ? $_POST['medicine_id'] : $medicineId;
$medicineId = mysqli_real_escape_string($conn, $medicineId);

// Check if the form is submitted
if ($_SERVER["REQUEST_METHOD"] == "POST") {
    $pricePerUnit = $_POST['price_per_unit'];
    $quantity = $_POST['quantity'];
    $expirationDate = $_POST['expiration_date'];
    $purchaseDate = $_POST['purchase_date'];

    // Verifications
    if ($pricePerUnit < 0 || $quantity < 0) {
        echo "<center>Price and quantity must not be negative.</center>";
        header("refresh:2;url=../addbatchmedicine.php?medicine_id=$medicineId");
        exit;
    }

    // Format price to always have two decimal places
    $pricePerUnit = number_format((float)$pricePerUnit, 2, '.', '');

    if (strtotime($expirationDate) <= strtotime($purchaseDate)) {
        echo "<center>Expiration date must be after the purchase date.</center>";
        header("refresh:2;url=../addbatchmedicine.php?medicine_id=$medicineId");
        exit;
    }

    $currentDate = date("Y-m-d");
    if (strtotime($purchaseDate) > strtotime($currentDate)) {
        echo "<center>Purchase date must not be after the current date.</center>";
        header("refresh:2;url=../addbatchmedicine.php?medicine_id=$medicineId");
        exit;
    }

    $checkInvoiceSql = "SELECT invoice_no FROM batch WHERE purchase_date = '$purchaseDate' AND medicine_id = '$medicineId' LIMIT 1";
    $checkInvoiceResult = $conn->query($checkInvoiceSql);
    
    if ($checkInvoiceResult) {
        // Check if the query was successful
        if ($checkInvoiceResult->num_rows > 0) {
            // Invoice exists in the batch table, reuse the existing invoice number
            $row = $checkInvoiceResult->fetch_assoc();
            $invoiceNo = $row['invoice_no'];
    
            // Calculate new cost based on quantity and price per unit
            $newCost = $quantity * $pricePerUnit;
    
            // Update the cost in the existing invoice in the invoice table by adding the new cost
            $updateInvoiceSql = "UPDATE invoice SET cost = cost + '$newCost' WHERE invoice_no = '$invoiceNo'";
    
            if ($conn->query($updateInvoiceSql) !== TRUE) {
                echo "Error: " . $updateInvoiceSql . "<br>" . $conn->error;
                exit;
            }
        } else {
            // Invoice does not exist in the batch table, create a new invoice
            $autoGeneratedInvoiceIdSql = "SELECT MAX(CAST(SUBSTRING(invoice_no, 4) AS SIGNED)) AS max_id FROM invoice";
            $result = $conn->query($autoGeneratedInvoiceIdSql);
    
            if ($result && $row = $result->fetch_assoc()) {
                // Extract the numeric part and increment
                $nextId = $row['max_id'] + 1;
    
                // Format the next ID as invX (e.g., inv1)
                $invoiceNo = 'inv' . $nextId;
            } else {
                $invoiceNo = 'inv1'; // Default to inv1 if there is an issue with the database query
            }
    
            // Calculate cost based on quantity and price per unit
            $cost = $quantity * $pricePerUnit;
    
            // Insert data into the invoice table
            $invoiceSql = "INSERT INTO invoice (invoice_no, cost, payment_reference, time_stamp)
                           VALUES ('$invoiceNo', '$cost', 'Medicine_Invoice', NOW())";
    
            if ($conn->query($invoiceSql) !== TRUE) {
                echo "Error: " . $invoiceSql . "<br>" . $conn->error;
                exit;
            }
        }
    } else {
        echo "Error in query: " . $conn->error;
        exit;
    }

    // Generate an auto-incremented Batch ID
    $autoGeneratedBatchIdSql = "SELECT MAX(CAST(SUBSTRING(batch_id, 3) AS SIGNED)) AS max_id FROM batch";
    $result = $conn->query($autoGeneratedBatchIdSql);

    if ($result && $row = $result->fetch_assoc()) {
        // Extract the numeric part and increment
        $nextId = $row['max_id'] + 1;

        // Format the next ID as btX (e.g., bt1)
        $batchId = 'bt' . $nextId;
    } else {
        $batchId = 'bt1'; // Default to bt1 if there is an issue with the database query
    }
    

    // Insert data into the batch table
    $batchSql = "INSERT INTO batch (batch_id, price_punit, quantity, quantity_stock, expiration_date, medicine_id, status, purchase_date, invoice_no)
                 VALUES ('$batchId', '$pricePerUnit', '$quantity', '$quantity', '$expirationDate', '$medicineId', 'Unused', '$purchaseDate', '$invoiceNo')";

    if ($conn->query($batchSql) === TRUE) {
        echo "<center>Batch '$batchId' Added Successfully</center>";
        header("refresh:2;url=../batchmedicine.php?id=$medicineId");
    } else {
        echo "Error: " . $batchSql . "<br>" . $conn->error;
    }
}
?>


<!-- Bootstrap Modal for Success Message -->
<div class="modal fade" id="successModal" tabindex="-1" role="dialog" aria-labelledby="successModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="successModalLabel">Success</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Batch added successfully!
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<!-- Bootstrap Modal for Error Message -->
<div class="modal fade" id="errorModal" tabindex="-1" role="dialog" aria-labelledby="errorModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="errorModalLabel">Error</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                An error occurred.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<script>
    // Show the success modal
    $('#successModal').modal('show');

    // Alternatively, you can show the error modal if there is an error
    // $('#errorModal').modal('show');
</script>